import { Box } from '@mui/material';
import { InferGetServerSidePropsType, InferGetStaticPropsType } from 'next';
import Head from 'next/head'
import LanguageTile from '../components/tiles/languageTile';
import { TileTemplate } from '../templates/tileTemplate/tileTemplate'
import { fetchLanguages } from './api/apiLanguages';
import Link from "next/link";

export async function getServerSideProps() {
  const languages = await fetchLanguages();
  return {
    props: {
      languages,
    },
  }
}

const LanguageSelection: React.FC<InferGetServerSidePropsType<typeof getServerSideProps>> = (props) => {
  return (
    <>
      <Head>
        <title>LaMa quiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TileTemplate maxItemsOnPage={8}>
        {props.languages.map(language => <Box key={language.iconUrl + language.culture} sx={{ maxHeight: "200px" }}>
          <Link href={`/${language.culture}/quiz`}><LanguageTile  {...language} /></Link>
        </Box>)}
      </TileTemplate>
    </>
  )
}

export default LanguageSelection;
